AB#52204 Added MtoaRequestService
tc-ca/MSS-Seafarer-Certification pull request #101
Opened 2020-11-30 13:57 UTC by tropical-turtle

2020-11-30 15:16 UTC, AlexandreSanscartier requested changes

2020-11-30 15:16 UTC, AlexandreSanscartier commented on CDTS Blazor/Models/PageModels/ReviewDocumentPageModel.cs
> +            this.confirmationGuid = this.Model.MtoaServiceRequestId;
Do we want the confirmationGuid to be the service request Id?

2020-11-30 15:16 UTC, AlexandreSanscartier commented on CDTS Blazor/Pages/UploadDocument.razor
> +        model.ConfirmationNumber = model.MtoaServiceRequestId.ToString();
Do we want the confirmationGuid to be the service request Id?

2020-11-30 15:16 UTC, AlexandreSanscartier commented on CDTS Blazor/Utilities/RestClient.cs
> +
Shouldn't need to add a new method to the RestClient
```suggestion
```

2020-11-30 15:16 UTC, AlexandreSanscartier commented on CDTS Blazor/Utilities/IRestClient.cs
> +
Shouldn't need to add this method we can use the PostAsync(ServiceLocatorDomain serviceName, string path, object dataObject = null);
```suggestion
```

2020-11-30 15:16 UTC, AlexandreSanscartier commented on CDTS Blazor/appsettings.json
> +    "ProgressStatus": "InProgress"
Is there a reason we're adding a progress status here? doesn't seem like the right place to put it.

2020-11-30 18:27 UTC, AlexandreSanscartier commented on CDTS Blazor/Models/PageModels/ReviewDocumentPageModel.cs
> +            this.confirmationGuid = this.Model.MtoaServiceRequestId;
Nvm we do lol

2020-12-02 14:17 UTC, tc-tibo commented
The PR links to issue #91

2020-12-02 20:09 UTC, merged