Ab#54500 google re captcha
tc-ca/MSS-Seafarer-Certification pull request #122
Opened 2021-01-05 06:01 UTC by tropical-turtle

Added Google reCatcha

2021-01-05 16:28 UTC, AlexandreSanscartier requested changes

2021-01-05 16:28 UTC, AlexandreSanscartier commented on src/CSF.Web/CSF.Web.Client/Pages/_Host.cshtml
> +    <script type="text/javascript" src="@string.Format(System.Globalization.CultureInfo.InvariantCulture, " {0}wet-{1}.js", WebTemplateModel.CDNPath, WebTemplateModel.TwoLetterCultureLanguage)"></scr
Remove space
```suggestion
    <script type="text/javascript" src="@string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0}wet-{1}.js", WebTemplateModel.CDNPath, WebTemplateModel.TwoLetterCultureLanguage)"></script>
```

2021-01-05 21:08 UTC, tropical-turtle commented on src/CSF.Web/CSF.Web.Client/Models/PageModels/UploadDocumentPageModel.cs
> +        [Required(ErrorMessage ="\"I'm not a robot\" field must be checked")]
Good point. Moved messaged to UploadDocumentValidator.cs and to the corresponding resource file.

2021-01-05 21:09 UTC, tropical-turtle commented on src/CSF.Web/CSF.Web.Client/Pages/UploadDocument.razor
> +    <DataAnnotationsValidator/>
Removed.

2021-01-05 21:10 UTC, tropical-turtle commented on src/CSF.Web/CSF.Web.Client/Pages/_Host.cshtml
> +    <script type="text/javascript" src="@string.Format(System.Globalization.CultureInfo.InvariantCulture, " {0}wet-{1}.js", WebTemplateModel.CDNPath, WebTemplateModel.TwoLetterCultureLanguage)"></scr
Good catch.Space removed. Not sure how that space got introduced.

2021-01-05 21:10 UTC, tropical-turtle commented on src/CSF.Web/CSF.Web.Client/Pages/_Host.cshtml
> +    <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>
Moved.

2021-01-05 21:11 UTC, tropical-turtle commented on src/CSF.Web/CSF.Web.Client/Pages/_Host.cshtml
> +    <script type="text/javascript" src="@string.Concat(WebTemplateModel.CDNPath, " soyutils.js")"></script>
Removed the space.

2021-01-06 15:46 UTC, AlexandreSanscartier requested changes
Added suggestion to localize the recaptcha.

2021-01-06 15:46 UTC, AlexandreSanscartier commented on src/CSF.Web/CSF.Web.Client/Pages/_Host.cshtml
> +    <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>
```suggestion
<script src="@string.Concat("https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit&hl=", @WebTemplateModel.TwoLetterCultureLanguage), " async defer"></script>
```

2021-01-06 17:16 UTC, AlexandreSanscartier approved these changes

2021-01-06 18:02 UTC, merged