Ab#56823 persist data from document submission app
tc-ca/MSS-Seafarer-Certification pull request #129
Opened 2021-02-10 13:18 UTC by tc-chris

2021-02-10 14:05 UTC, tropical-turtle requested changes

2021-02-10 14:05 UTC, tropical-turtle commented on src/CSF.Web/CSF.Web.Client/Data/Services/MtoaArtifactService.cs
> +            int serviceRequestId = int.Parse(this.configuration.GetSection("MtoaServiceSettings")["ServiceRequestId"]);
serviceRequestID needs to be taken from the page model. Page model currently has the dynamically generated Service request ID. So, it needs to be
            int serviceRequestId = model.MtoaServiceRequestId;

2021-02-10 14:05 UTC, tropical-turtle commented on src/CSF.Web/CSF.Web.Client/Data/Services/MtoaArtifactService.cs
> +        private readonly string baseURL = "https://wwwappstest.tc.gc.ca/Saf-Sec-Sur/13/MTAPI-INT/api/v1/"; //This is for Dev only works within organizational network.
Let's use RestClient and in the RestClient BaseURL is set inside of RestClient.

2021-02-10 14:05 UTC, tropical-turtle commented on src/CSF.Web/CSF.Web.Client/Data/Services/MtoaArtifactService.cs
> +            HttpClient client = new HttpClient();
Let's use the RestClient instead of creating a new HttpClient .

2021-02-11 16:15 UTC, AlexandreSanscartier approved these changes

2021-02-11 16:57 UTC, merged