Ab#54608 add mtoa aftifact service
tc-ca/MSS-Seafarer-Certification pull request #130
Opened 2021-02-10 14:31 UTC by tropical-turtle

Added data loading mechanism from MTOA

2021-02-10 15:52 UTC, AlexandreSanscartier requested changes

2021-02-10 15:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/DTO/ServiceRequest.cs
> +            return null;
Is there a reason this method returns null? Should probably either have it return something or just remove this function.

2021-02-10 15:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/MtoaArtifactService.cs
> +        public int GetNumberOfRequestForSeafarers()
I believe you can remove this call and use the next one to get the number of requests. That way we get information while getting the number of requests. We can eliminate one call this way.

2021-02-10 15:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/MtoaArtifactService.cs
> +        public List<ServiceRequest> GetAllRequestsForSeafarers(int numberOfRequest)
I'm not sure we ever want to get all requests I would change the name of the parameter. We probably want to move this to MtoaService class.
```suggestion
        public List<ServiceRequest> GetAllRequestsForSeafarers(int pageSize)
```

2021-02-10 15:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/MtoaArtifactService.cs
> +        public SeafarersArtifactDTO GetArtifactByArtifactId(int artifactId)
We probably want to move this to MtoaService class.

2021-02-10 15:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/MtoaArtifactService.cs
> +        public SeafarersArtifactDTO GetArtifactByServiceRequestId(int serviceRequestId)
We probably want to move this to MtoaService class.

2021-02-10 15:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/DTO/IServiceRequestMetadata.cs
> +    public interface IServiceRequestMetadata
This interface is never used.

2021-02-10 15:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/DTO/ServiceRequest.cs
> +        public IServiceRequestMetadata Metadata { get; set; }
This interface is never used remove it.

2021-02-10 18:34 UTC, tc-chris commented on src/CSF.SRDashboard.Client/DTO/ServiceRequestCollection.cs
> +        public ServiceRequestCollection()
The constructor isn't being used, maybe remove it.

2021-02-10 18:34 UTC, tc-chris commented on src/CSF.SRDashboard.Client/DTO/ServiceRequestDTO.cs
> +        {
The constructor isn't being used, maybe remove it.

2021-02-10 18:34 UTC, tc-chris commented on src/CSF.Web/CSF.Web.Client/Utilities/RestClient.cs
> +            response = await this.httpClient.GetAsync(uri).ConfigureAwait(false);
response = await this.httpClient.GetAsync(uri).GetAwaiter().GetResult(); instead

2021-02-10 19:43 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/BaseServiceRequest.cs
> +        [JsonProperty(Order = -17)]
This model comes from MTOA library. I did not modify their library. I used it as is.

2021-02-10 19:43 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/ServiceRequest.cs
> +            return null;
This is also how it is inside MTOA library. I did not spend much time on it why.

2021-02-10 19:45 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/MtoaArtifactService.cs
> +        public List<ServiceRequest> GetAllRequestsForSeafarers(int numberOfRequest)
Getting all the request was the idea that we came up with the team I believe. Tibo suggested this way of loading data.

2021-02-10 19:55 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/MtoaArtifactService.cs
> +        public SeafarersArtifactDTO GetArtifactByArtifactId(int artifactId)
GetArtifactByArtifactId(int artifactId) is Artifact Related method. 
And it is why it was placed in here. Becasue of some changes I made. This method actually not use.
Even removing this is ok too.

2021-02-10 20:12 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/MtoaArtifactService.cs
> +        public SeafarersArtifactDTO GetArtifactByServiceRequestId(int serviceRequestId)
I agree to some degree. Both Artifact Service and Service Requests provide similar methods, but with different API verb formats.
The ones provide are:
Artifact Service
v1/artifacts?serviceRequestId=22016&artifactType=JsonMetadata

Service Requests
v1/servicerequests/22016/artifacts

In our current implementation, I used the verb format:
v1/artifacts?serviceRequestId=22016&artifactType=JsonMetadata
It is why I kept it inside MtoaArtifactService

2021-02-10 20:17 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/IServiceRequestMetadata.cs
> +    public interface IServiceRequestMetadata
This also came as part of MTOA DTO objects.
I did not modify. Used as is.
Some of our team members did not have access to TC nuget package. We had to copy-paste those DTO definitions. :)

2021-02-10 20:21 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/ServiceRequest.cs
> +        public IServiceRequestMetadata Metadata { get; set; }
This also came from MTOA objects. Did not modify. Used as is.

2021-02-10 20:21 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/ServiceRequestCollection.cs
> +        public ServiceRequestCollection()
This also comes from MTOA objects. Did not modify. Used as is.

2021-02-10 20:23 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/ServiceRequestDTO.cs
> +        {
This also comes from MTOA objects . did not modify. Used as is.

2021-02-10 20:25 UTC, tropical-turtle commented on src/CSF.Web/CSF.Web.Client/Utilities/RestClient.cs
> +            response = await this.httpClient.GetAsync(uri).ConfigureAwait(false);
RestClient code was written by @TCPrimedPaul . Tried making minimal change.

2021-02-10 20:26 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/DTO/IServiceRequestMetadata.cs
> +    public interface IServiceRequestMetadata
The interface is empty it functionally does nothing.

2021-02-11 02:42 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/MtoaArtifactService.cs
> +        public int GetNumberOfRequestForSeafarers()
On the next one , the pageSize is determined by the number of Request. That is why this first call was made.

2021-02-11 02:48 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/IServiceRequestMetadata.cs
> +    public interface IServiceRequestMetadata
Removed.

2021-02-11 02:48 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/ServiceRequest.cs
> +        public IServiceRequestMetadata Metadata { get; set; }
Removed.

2021-02-11 02:50 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/ServiceRequestCollection.cs
> +        public ServiceRequestCollection()
Removed

2021-02-11 02:55 UTC, tropical-turtle commented on src/CSF.Web/CSF.Web.Client/Utilities/RestClient.cs
> +            response = await this.httpClient.GetAsync(uri).ConfigureAwait(false);
Changed

2021-02-11 02:58 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/ServiceRequest.cs
> +        public ServiceRequest(BaseServiceRequest dto)
Removed

2021-02-11 14:50 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/ServiceRequest.cs
> +            return null;
Removed

2021-02-11 15:09 UTC, AlexandreSanscartier requested changes

2021-02-11 15:09 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/DTO/ServiceRequestDTO.cs
> +        public ServiceRequestDTO()
This constructor doesn't do anything code can be removed.

2021-02-11 15:09 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/MtoaArtifactService.cs
> +        public List<ServiceRequest> GetAllRequestsForSeafarers(int numberOfRequests)
I believe this should be renamed as suggested as this is what the parameter does.
```suggestion
        public List<ServiceRequest> GetAllRequestsForSeafarers(int pageSize)
```

2021-02-11 15:09 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/MtoaArtifactService.cs
> +        public int GetNumberOfRequestForSeafarers()
I believe we don't need this call as the other one gets that information as well and we'd just be making two calls that we don't need to make.

2021-02-11 15:09 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/MtoaArtifactService.cs
> +        public SeafarersArtifactDTO GetArtifactByServiceRequestId(int serviceRequestId)
I still strongly believe we should move this here: We probably want to move this to MtoaService class.

2021-02-11 15:09 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/MtoaArtifactService.cs
> +        public List<ServiceRequest> GetAllRequestsForSeafarers(int numberOfRequests)
We probably want to move this to MtoaService class.

2021-02-11 15:16 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/MtoaArtifactService.cs
> +        public List<ServiceRequest> GetAllRequestsForSeafarers(int numberOfRequests)
changed

2021-02-11 15:18 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/ServiceRequestDTO.cs
> +        public ServiceRequestDTO()
Removed.

2021-02-11 17:46 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/MtoaArtifactService.cs
> +        public int GetNumberOfRequestForSeafarers()
Removed.

2021-02-11 17:59 UTC, AlexandreSanscartier requested changes

2021-02-11 17:59 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/_Host.cshtml
> +    <component type="typeof(App)" render-mode="Server" />
Why is this changed to Server?

2021-02-11 17:59 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/IMtoaArtifactService.cs
> -        public List<ServiceRequest> GetAllRequestsForSeafarers(int numberOfRequest);
I think we wanted to keep this one since it's probably the one we'll be using for paging purposes.

2021-02-11 18:01 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/_Host.cshtml
> +    <component type="typeof(App)" render-mode="Server" />
Otherwise page OnInitialized is triggered twice and data is loading twice.

2021-02-15 19:29 UTC, AlexandreSanscartier approved these changes

2021-02-15 19:29 UTC, merged