Ab#69372 adding azure ad
tc-ca/MSS-Seafarer-Certification pull request #141
Opened 2021-03-11 15:25 UTC by tropical-turtle

Added Azure Active directory integration.

2021-03-11 16:01 UTC, AlexandreSanscartier requested changes
A few changes nothing dramatic good work!

2021-03-12 18:36 UTC, AlexandreSanscartier requested changes
Looks good just take a look at my previous comments and let me know what you think before we close this.

2021-03-12 18:56 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/GraphApiService.cs
> +    public class GraphApiService : IGraphApiService
Good point.

2021-03-12 18:56 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Shared/LoginDisplay.razor.cs
> +        }
Good point.

2021-03-12 18:56 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/IGraphApiService.cs
> +    public interface IGraphApiService
Good point.

2021-03-12 21:27 UTC, AlexandreSanscartier approved these changes
Good work!

2021-03-12 21:27 UTC, merged