Ab#85435 attach document through UI
tc-ca/MSS-Seafarer-Certification pull request #156
Opened 2021-05-21 20:58 UTC by TC-Cory

2021-05-22 00:07 UTC, AlexandreSanscartier requested changes
A few changes, but overall good job. Just take care of the styling.

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/AddDocumentComponent.razor.cs
> +            this.NavigationManager.NavigateTo($"/SeafarerProfile/{this.Cdn}");
We could simplify to this. 
```suggestion
            this.FileToUpload = null;
            this.NavigationManager.NavigateTo($"/SeafarerProfile/{this.Cdn}");
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/Dashboard/DashboardTable.razor.cs
> +        }
```suggestion       NavigationManager.NavigateTo($"/SeafarerProfile/{this.Applicant.Cdn}/AddAttachment");
        }
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/UploadDocumentComponent.razor
> +
```suggestion
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/UploadDocumentComponent.razor.cs
> +
```suggestion
        private IFormFile formFile;
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/UploadDocumentComponent.razor.cs
> +
```suggestion
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/UploadDocumentComponent.razor.cs
> +
```suggestion
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Models/AddDocumentModel.cs
> +
```suggestion
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/PageValidators/AddAttachmentValidator.cs
> +
```suggestion
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/PageValidators/SearchValidator.cs
> +
```suggestion
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/AddDocument.razor.cs
> +
```suggestion
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/AddDocument.razor.cs
> +
```suggestion
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/FindSeafarer.razor
> +
```suggestion
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/FindSeafarer.razor
> +
```suggestion
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor
> +                <CSF.SRDashboard.Client.Components.Tables.WorkloadRequest.WorkloadRequestTable />
```suggestion       <CSF.SRDashboard.Client.Components.Tables.WorkloadRequest.WorkloadRequestTable />
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor.cs
> +
```suggestion
```

2021-05-22 00:07 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/_Host.cshtml
> +    <script src="_content/Radzen.Blazor/Radzen.Blazor.js"></script>
```suggestion
```

2021-05-25 13:23 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/Components/AddDocumentComponent.razor.cs
> +                    DocumentId = result[0]
Result[0] is the is the first entry in the list of GUIDs that the method returns

2021-05-25 13:59 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/AddDocumentComponent.razor.cs
> +                    DocumentId = result[0]
I know that, but the next person who comes in the team isn't go to know that just by reading your code, which is why I suggest changing the variable name so that we don't have to explain it to the next dev that joins.

2021-05-25 14:10 UTC, AlexandreSanscartier requested changes
Suggest a quick rename to a variable to explicitly explain what it doesn.

2021-05-25 14:56 UTC, AlexandreSanscartier approved these changes
Everything's good! Nice work!

2021-05-25 15:14 UTC, merged