Ab#86950 create new request
tc-ca/MSS-Seafarer-Certification pull request #157
Opened 2021-05-25 18:56 UTC by tc-chris

2021-05-26 14:25 UTC, TC-Cory reviewed
Looks good, tested and working well

2021-05-26 16:52 UTC, AlexandreSanscartier requested changes
Overall good job! Some styling suggestions. A few places to check the logic to make sure it's all good and a few suggestions for reducing lines of code, as well as some  readability suggestions.

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor
> +
Remove commented code.
```suggestion
```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +
```suggestion
```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +        public NavigationManager NavigationManager { get; set; }
This is better so we can have all parameters and inject properties and then all public properties.
```suggestion
        [Inject]
        public IGatewayService GatewayService { get; set; }

        [Inject]
        public IWorkLoadManagementService WorkLoadService { get; set; }

        [Inject]
        public NavigationManager NavigationManager { get; set; }
        
         public string Comment { get; set; }
```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +
```suggestion
```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +
```suggestion
```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +            this.Applicant = this.GatewayService.GetApplicantInfoByCdn(Cdn);
We're setting this twice? I'm not sure if this is necessary, but perhaps we should just do the second call.
```suggestion
            this.Applicant = this.GatewayService.GetApplicantInfoByCdn(Cdn);
```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/FindSeafarer.razor.cs
> +                if (this.State.ApplicantSearchResult != null && this.State.ApplicantSearchResult.TotalCount > 0)
We might want to consider creating a private bool function and naming it accordingly in this case I believe something like this would be appropriate

private bool hasSearchResults() {
var applicantSearchResult =  this.State.ApplicantSearchResult;
return applicantSearchResult  != null && applicantSearchResult.TotalCount > 0
}

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor
> +</div>
I remember working on this yesterday together I believe we don't need the container div anymore.
```suggestion
    <AlertComponent ShowIcon="false" AlertType="@alertType" EnableShow="@IsAlertEnabled" Dismisable="true">
        <ChildContent>
            <p>You successfully created request #@requestId for <strong> @Applicant.FullName </strong></p>
        </ChildContent>
    </AlertComponent>
```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor.cs
> +
Remove unnecessary extra line breaks.
```suggestion
```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor.cs
> +
I'm assuming it's a class  variable, but for readability we probably want to preface it with this. This line can be simplified to
```suggestion
            this.IsAlertEnable = requested != 0;
```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor.cs
> +            }
Careful if the convert fails this will throw an exception. It will either throw a FormatException if requestId is not a valid Int32  or it will throw an OverflowException if the number  is greater than an Int32
```suggestion
            if (QueryHelpers.ParseQuery(uri.Query).TryGetValue("requestId", out var requestId))
            {
                RequestID = Convert.ToInt32(requestId);
            }
```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor.cs
> +        public AlertTypes alertType { get; set; }
Public properties start with an uppercase
```suggestion
        public AlertTypes AlertType { get; set; }
```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor.cs
> +        public int requestId { get; set; }
Public properties start with an uppercase.
```suggestion
        public int RequestId { get; set; }
```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor.cs
> +            alertType = AlertTypes.Success;
```suggestion
            this.TableItems = WorkLoadService.GetByCdnInRequestTableFormat(Cdn);
            this.AlertType = AlertTypes.Success;
```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/Constants.cs
> +        public const string MarineMedical = "002";
Should this be here or in the appsettings? Or in our keyvalut?

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/IWorkLoadManagementService.cs
> +        List<WorkloadRequestTableItem> GetByCdnInRequestTableFormat(string cdn);
We could consider adding documentation to these methods.
```suggestion
        WorkItemDTO GetByWorkItemById(int id);
        
        List<WorkItemDTO> GetByLineOfBusinessId(string lineOfBusinessId);
        
        WorkItemDTO AddWorkItem(WorkItemDTO workItem);
        
        List<WorkItemDTO> GetByCdnNumber(string cdn);
        
        WorkItemDTO PostRequestModel(RequestModel requestModel, IGatewayService gatewayService);
        
        List<WorkloadRequestTableItem> GetByCdnInRequestTableFormat(string cdn);
```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +
```suggestion

```

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +                return null;
We want to be careful about returning null values and make sure we handle them properly. In this case it may be better to send an empty list.

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +            contact.ContactUniqueId = requestModel.Cdn;
We could  probably create a private method for this in this class since I have a feeling we'll be reusing this a few times.

2021-05-26 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +            string itemDetailString = JsonSerializer.Serialize(itemDetail);
We could  probably create a private method for this in this class since I have a feeling we'll be reusing this a few times.

2021-05-26 19:37 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/Components/AddDocumentComponent.razor
> +<div style="width:707px;">
this will be fixed in attach document to a seafarer PBI

2021-05-27 12:23 UTC, tc-chris commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +                return null;
I agree, good idea

2021-05-28 20:44 UTC, tropical-turtle commented on src/CSF.Common.Library/Rest/AbstractRestClient.cs
> +
Removed.

2021-05-28 20:45 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/CSF.SRDashboard.Client.csproj
> +  <ItemGroup>
Used for testing when debugging. I thought that folder was ignored on Git for some reason it got included. Good observation.  :)
Removed.

2021-05-28 20:49 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Components/Tables/Dashboard/DashboardTable.razor
> +                <a href="@Document.DownloadLink" style="text-decoration: underline;">@Document.FileName</a>
Replaced

2021-05-28 20:52 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/Entities/WorkloadRequestTableItem.cs
>              public string Language { get; set; }
Changed

2021-05-28 20:54 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/WorkloadRequestTable.razor.cs
>          }
Removed.

2021-05-28 20:54 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/WorkloadRequestTable.razor.cs
>          }
Removed

2021-05-28 20:58 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/WorkloadRequestTableItemPriorityComponent.razor.cs
> +                    return false;
Replaced

2021-05-28 20:58 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/WorkloadRequestTableItemPriorityComponent.razor.cs
> +                    return false;
Replaced

2021-05-28 21:00 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/WorkLoadManagement/ContactInformationDTO.cs
> +        public DateTime? DeletedDateUTC { get; set; }
Changed.

2021-05-28 21:01 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/WorkLoadManagement/WorkItemCommentsDTO.cs
> +        public bool IsDeleted { get; set; }
Changed.

2021-05-28 21:03 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/WorkLoadManagement/WorkItemDTO.cs
> +        public WorkItemAssignmentDTO WorkItemAssignment { get; set; }
Changed.

2021-05-28 21:03 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/WorkLoadManagement/WorkItemStatusDTO.cs
> +        public string StatusChangeEmployeeId { get; set; }
Changed.

2021-05-28 21:05 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/WorkLoadManagement/WorkItemDetail.cs
> +        public List<RequestComment> Comments { get; set; }
Changed.

2021-05-28 21:06 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Models/Dropdown.cs
> +    }
Changed.

2021-05-28 21:07 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Models/RequestComment.cs
> +
Changed.

2021-05-28 21:09 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/PageValidators/RequestValidator.cs
> +}
Changed.

2021-05-28 21:21 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +            contact.ContactUniqueId = requestModel.Cdn;
Created a separate private method for getting ContactInfo

2021-05-28 21:41 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +            string itemDetailString = JsonSerializer.Serialize(itemDetail);
Created a private method for WorkItemDetail

2021-05-28 21:44 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor
> +        @*<button id="SeafarerCancel" type="button" class="btn btn-light btn-clear mr-3">Cancel</button>*@
Removed

2021-05-28 21:45 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/WorkLoadManagement/WorkItemAssignmentDTO.cs
> +        public System.DateTimeOffset? DeletedDateUTC { get; set; }
Changed.

2021-05-28 21:46 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/DTO/WorkLoadManagement/WorkItemAttachmentDTO.cs
> +        public System.Guid DocumentId { get; set; }
Changed

2021-05-29 02:42 UTC, tropical-turtle commented on src/CSF.Common.Library/Rest/AbstractRestClient.cs
> +            string result = null;
Restructured the method

2021-05-29 02:43 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Components/AddDocumentComponent.razor
> +<div style="width:707px;">
Based on Cory this will be addressed on a different PBI

2021-05-29 02:45 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/WorkloadRequestTable.razor.cs
> +
Removed

2021-05-29 03:22 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor
> +
Removed

2021-05-29 03:23 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +
Removed

2021-05-29 03:26 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +        public NavigationManager NavigationManager { get; set; }
Re-organized

2021-05-29 03:26 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +
Removed

2021-05-29 03:27 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +
Removed

2021-05-29 03:29 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +            this.Applicant = this.GatewayService.GetApplicantInfoByCdn(Cdn);
They got merged in together by accident.
Removed one.

2021-05-29 03:32 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor
> +</div>
Removed

2021-05-29 03:35 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor.cs
> +
Changed

2021-05-29 03:40 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor.cs
> +            }
Changed

2021-05-29 03:43 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor.cs
> +
Removed

2021-05-29 03:44 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor.cs
> +        public AlertTypes alertType { get; set; }
Changed

2021-05-29 03:45 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor.cs
> +        public int requestId { get; set; }
Changed

2021-05-29 03:47 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor.cs
> +            alertType = AlertTypes.Success;
Changed

2021-05-29 03:50 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +
Removed

2021-05-29 04:07 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +
Removed

2021-05-29 04:22 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/IWorkLoadManagementService.cs
> +        List<WorkloadRequestTableItem> GetByCdnInRequestTableFormat(string cdn);
Added spacing and also added documentation

2021-05-29 04:37 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Pages/FindSeafarer.razor.cs
> +                if (this.State.ApplicantSearchResult != null && this.State.ApplicantSearchResult.TotalCount > 0)
Added a private method

2021-05-29 04:40 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +                return null;
Changed

2021-05-29 04:42 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +                return null;
This was intentional to mean that it returns null when nothing is found for the given work item id

2021-05-29 04:43 UTC, tropical-turtle commented on src/CSF.SRDashboard.Client/Services/Constants.cs
> +        public const string MarineMedical = "002";
It was placed in here to make the future unit tests simpler, otherwise in the unit tests we will have to pass the Configuration. We can still move this to config file if you insist.  :)

2021-05-31 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/DTO/WorkLoadManagement/WorkItemDTO.cs
>          public string LineOfBusinessId { get; set; }
```suggestion
        public string LineOfBusinessId { get; set; }
        
```

2021-05-31 16:52 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +
```suggestion
```

2021-05-31 16:53 UTC, AlexandreSanscartier approved these changes

2021-05-31 17:51 UTC, merged