Ab#105023 request status history
tc-ca/MSS-Seafarer-Certification pull request #177
Opened 2021-07-07 19:20 UTC by TC-Cory

2021-07-08 20:15 UTC, AlexandreSanscartier requested changes
Nice work a few minor changes though.

2021-07-08 20:15 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestHistoryComponent.razor
> +            @if (this.StatusHistories == null || !this.StatusHistories.Any())
We could replace this with a function AreThereItemsToDisplay or something like that.

2021-07-08 20:15 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestHistoryComponent.razor
> +                <li class="StatusHistoryList-item @this.SetListCSS(i)">
You could us the first-child selector https://www.w3schools.com/cssref/sel_firstchild.asp instead of using different classes.

2021-07-08 20:15 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestHistoryComponent.razor.cs
> +        public string SetListCSS(int index)
See above comment for https://www.w3schools.com/cssref/sel_firstchild.asp

2021-07-08 20:15 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +            }
Avoid using empty if statement just reverse the if statement to remove the empty if.
```suggestion
            if (!this.VerifyStatusDuplicate(tempWorkItemJson.Status.First(), requestModel)) {
                tempWorkItemJson.Status.Insert(0, new StatusHistoryItem()
                {
                    ProcessingPhase = requestModel.ProcessingPhase,
                    StatusText = requestModel.Status,
                    ChangedBy = string.IsNullOrEmpty(requestModel.LoggedInUser) ? "Not assigned" : requestModel.LoggedInUser,
                    RequestStatusTime = DateTime.UtcNow
                }
                );
            }
```

2021-07-08 20:15 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +        private bool VerifyStatusDuplicate(StatusHistoryItem historyItem, RequestModel requestModel) => string.Equals(requestModel.ProcessingPhase, historyItem.ProcessingPhase) && string.Equals(reque
When dealing with booleans you can just send the statement you don't need to use ? true : false
```suggestion
        private bool VerifyStatusDuplicate(StatusHistoryItem historyItem, RequestModel requestModel) => string.Equals(requestModel.ProcessingPhase, historyItem.ProcessingPhase) && string.Equals(requestModel.Status, historyItem.StatusText);
```

2021-07-09 17:36 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestHistoryComponent.razor
> +                <li class="StatusHistoryList-item @this.SetListCSS(i)">
This has been implemented and tested.

2021-07-09 17:36 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestHistoryComponent.razor.cs
> +        public string SetListCSS(int index)
Done

2021-07-09 17:37 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +            }
Changes have been made

2021-07-09 17:37 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/Services/WorkLoadManagementService.cs
> +        private bool VerifyStatusDuplicate(StatusHistoryItem historyItem, RequestModel requestModel) => string.Equals(requestModel.ProcessingPhase, historyItem.ProcessingPhase) && string.Equals(reque
Fixed

2021-07-12 14:10 UTC, AlexandreSanscartier requested changes
Small change

2021-07-12 14:10 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestHistoryComponent.razor.cs
> +        public bool IsListEmpty() => this.StatusHistories == null ? false : true;
```suggestion
        public bool IsListEmpty() => this.StatusHistories == null || !this.StatusHistories.Any() ? false : true;
```

2021-07-15 17:13 UTC, AlexandreSanscartier requested changes

2021-07-15 17:13 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestHistoryComponent.razor.cs
> +        public bool IsListEmpty() => this.StatusHistories == null || !this.StatusHistories.Any() ? false : true;
```suggestion
        public bool IsListEmpty() => !(this.StatusHistories == null || !this.StatusHistories.Any())
```

2021-07-15 18:17 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestHistoryComponent.razor.cs
> +        public bool IsListEmpty() => this.StatusHistories == null || !this.StatusHistories.Any() ? false : true;
done!

2021-07-26 16:47 UTC, merged