Ab#111548 authenticat workload management
tc-ca/MSS-Seafarer-Certification pull request #178
Opened 2021-07-12 17:13 UTC by AlexandreSanscartier

2021-07-12 19:56 UTC, tc-chris requested changes

2021-07-12 19:56 UTC, tc-chris commented on src/CSF.SRDashboard.Client/Graph/GraphConstants.cs
> +            "https://034gc.onmicrosoft.com/ncd-wms-dev/WorkItem.Read.All",
Shouldn't these be in appsettings.json?

2021-07-12 19:56 UTC, tc-chris commented on src/CSF.SRDashboard.Client/appsettings.json
> +    "Scopes": "https://034gc.onmicrosoft.com/ncd-wms-dev/WorkItem.Read.All https://034gc.onmicrosoft.com/ncd-wms-dev/WorkItem.CreateUpdate.All"
Why do we have them in one line and not in an array?

2021-07-12 21:00 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/appsettings.json
> +    "Scopes": "https://034gc.onmicrosoft.com/ncd-wms-dev/WorkItem.Read.All https://034gc.onmicrosoft.com/ncd-wms-dev/WorkItem.CreateUpdate.All"
This is how the DownstreamWebAPI works. You need them specifically like that in order for it to work.

2021-07-12 21:00 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Graph/GraphConstants.cs
> +            "https://034gc.onmicrosoft.com/ncd-wms-dev/WorkItem.Read.All",
Will remove them, good catch I believe we don't need them in there.

2021-07-13 13:59 UTC, tc-chris commented on src/CSF.SRDashboard.Client/appsettings.json
> +    "Scopes": "https://034gc.onmicrosoft.com/ncd-wms-dev/WorkItem.Read.All https://034gc.onmicrosoft.com/ncd-wms-dev/WorkItem.CreateUpdate.All"
Okay

2021-07-13 15:46 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/Pages/ViewRequestDetails.razor.cs
> +            WorkItemDTO = await this.WorkLoadService.GetByWorkItemById(RequestId);
Not sure if you've received this error as well, I am getting a null reference on the RequestModel in AssigneeSelector.razor.cs. I've worked around this by initializing RequestModel before loading the workItem.

2021-07-16 14:25 UTC, merged