Ab#81864 request language
tc-ca/MSS-Seafarer-Certification pull request #180
Opened 2021-07-15 21:19 UTC by DarrenMes-tc

have to use "WorkLoadManagement": "http://work-management-service-dev.azurewebsites.net" endpoint to test.

2021-07-19 18:29 UTC, tc-chris requested changes

2021-07-19 18:29 UTC, tc-chris commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +            else if (Applicant.SelectedLanguage.Equals("fn", StringComparison.OrdinalIgnoreCase))
Is this an error? Shouldn't it be fr and not fn?

2021-07-20 13:44 UTC, DarrenMes-tc commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +            else if (Applicant.SelectedLanguage.Equals("fn", StringComparison.OrdinalIgnoreCase))
Yeah you're right. Made the change.

2021-07-20 14:21 UTC, tc-chris approved these changes
Looks good, well done

2021-07-20 18:04 UTC, merged