Ab#81881 request comments
tc-ca/MSS-Seafarer-Certification pull request #181
Opened 2021-07-19 19:47 UTC by TC-Cory

2021-07-21 14:50 UTC, AlexandreSanscartier requested changes
Just some styling changes, other than that looks good!

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestCommentComponent.razor.cs
> +        private bool areAllCommentsShown { get; set; } = false;
```suggestion
        [Parameter]
        public bool ReadOnly { get; set; }
        
        [Parameter]
        public EventCallback<string> SubmitComment { get; set; }
        
        [Parameter]
        public EventCallback<List<RequestCommentInfo>> WorkCommentsChanged { get; set; }
        
        [Inject]
        public IHttpContextAccessor httpContextAccessor { get; set; }
        
        [Inject]
        public IStringLocalizer<Shared.Common> Localizer { get; set; }
        
        public EditContext EditContext { get; set; }
        
        public RequestComment RequestComment { get; set; } = new RequestComment();
        
        private SortOption SortOption { get; set; } = new SortOption();
        
        private List<RequestCommentInfo> workComments { get; set; }
        
        private int maxShownComments { get; set; } = 5;
        
        private bool areAllCommentsShown { get; set; } = false;
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestCommentComponent.razor.cs
> +
```suggestion
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestCommentComponent.razor.cs
> +            if(this.maxShownComments > this.WorkComments.Count)
```suggestion
            }
            this.maxShownComments += 1;
            if(this.maxShownComments > this.WorkComments.Count)
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestCommentComponent.razor.cs
> +
```suggestion
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestCommentComponent.razor.cs
> +
```suggestion
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestCommentComponent.razor.cs
> +        private void setMaxToCurrentCount()
```suggestion
        }
        
        private void setMaxToCurrentCount()
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestCommentComponent.razor.cs
> +    }
Is there a reason this is a partial class? We should move this to its own file.

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/PageValidators/CommentValidator.cs
> +                 }
```suggestion
        public CommentValidator() {
            this.RuleFor(i => i.Comment).NotEmpty().WithMessage("Please enter a comment before submitting");
        }
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +        public List<RequestCommentInfo> WorkComments { get; set; } = new List<RequestCommentInfo>();
```suggestion
        public List<RequestCommentInfo> WorkComments { get; set; } = new List<RequestCommentInfo>();
        
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/CreateNewRequest.razor.cs
> +        }
```suggestion
        }
        
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/EditNewRequest.razor.cs
> +
```suggestion
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/ViewRequestDetails.razor.cs
> +        public SessionState State { get; set; }
```suggestion
        public SessionState State { get; set; }
        
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/ViewRequestDetails.razor.cs
> +
```suggestion
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/ViewRequestDetails.razor.cs
> +
```suggestion
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/ViewRequestDetails.razor.cs
> +
```suggestion
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/ViewRequestDetails.razor.cs
> +
```suggestion
```

2021-07-21 14:50 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/ViewRequestDetails.razor.cs
> +
```suggestion
```

2021-07-22 15:03 UTC, AlexandreSanscartier requested changes

2021-07-22 15:03 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestCommentComponent.razor.cs
> +        private bool isCommentListEmpty() => !(this.WorkComments == null || !this.WorkComments.Any());
We need to change this statement to the following or fix the variable name. 
```suggestion
        private bool isCommentListEmpty => this.WorkComments== null || !this.WorkComments.Any();
```

2021-07-22 18:07 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestCommentComponent.razor.cs
> +        private bool isCommentListEmpty() => !(this.WorkComments == null || !this.WorkComments.Any());
Done

2021-07-22 18:09 UTC, merged