[AB#118003-Ensure-all-dates-are-in-the-appropriate-language-when-disp…
tc-ca/MSS-Seafarer-Certification pull request #191
Opened 2021-08-09 14:06 UTC by tc-chris

…layed] AB#118524 - Change the dates to be showed in french also

2021-08-09 18:27 UTC, AlexandreSanscartier requested changes
Overall good concept, I suggested changes related to future maintainability and readability. There were also a few places where we had parameters that were unused that could most likely be removed.

2021-08-09 18:27 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/WorkloadRequestTable.razor.cs
> +                var t = Culture;
var t doesn't seem to be used anywhere we could get rid of it.
```suggestion
```

2021-08-09 18:27 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Pages/SeafarerProfile.razor.cs
> +                    DateUploadFormatted = CommonService.DateFormat(documentInfo.DateLastUpdated.Value, "MMM dd, yyyy"),
Suggest removing this line and instead inject the CommonService in the DashboardTable instead.
```suggestion
```

2021-08-09 18:27 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Models/Document.cs
> +        public string DateUploadFormatted { get; set; }
Suggest removing the DateUploadFormatted and instead format DateUploaded using the CommonService wherever we want the formatted value.
```suggestion
```

2021-08-09 18:27 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Models/SeafarerDetailsModel.cs
> +        public string DateOfBirthFormatted { get; set; }
Does not seem to be used anywhere could probably be removed.
```suggestion
```

2021-08-09 18:27 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Models/SeafarerDetailsModel.cs
> +        public string DateOfExpiryFormatted { get; set; }
Does not seem to be used anywhere could probably be removed.
```suggestion
```

2021-08-09 18:27 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/CommonService.cs
> +        public string DateFormat(DateTime dateToFormat, string format, string language = null)
It seems this function is never called with the language parameter set, so it will always return English as the formatted date. We could also add an enum for language possibly since we will probably only ever have two values English / French.

2021-08-09 18:27 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/CommonService.cs
> +            if (language.Equals("Fr", StringComparison.OrdinalIgnoreCase))
Though technically it doesn't matter in which case we have "fr" I'd suggest for consistency's sake to have both letters in the same case. Also adding a read-only parameter "fr" to the class to avoid using magic strings.
```suggestion
            if (language.Equals("fr", StringComparison.OrdinalIgnoreCase))
```

2021-08-09 18:27 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/CommonService.cs
> +                culture = new CultureInfo("fr-CA");
Same here we could have a read-only parameter for FrenchCulture = "fr-CA" and replace the magic string with that. I've attached a few online resources explaining why it's important to avoid using magic strings / numbers:
[Plural Sights - Avoiding magic numbers](https://www.pluralsight.com/tech-blog/avoiding-magic-numbers/)
[Stackoverflow - What is a magic number and why it's bad](https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad)

2021-08-09 18:27 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/CommonService.cs
> +            var charsToRemove = new string[] { "." };
Is there a reason we are removing the period from the date?

2021-08-09 18:27 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Services/CommonService.cs
> +        }
This method is never called and can most likely be removed.
```suggestion
```

2021-08-09 18:27 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Models/RequestModel.cs
> +        public string DueDateFormatted { get; set; }
Same as the Document model I suggest removed the DueDateFormatted and instead inject the CommonService in the RequestionInformation.razor.cs

2021-08-09 18:27 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/RequestHistoryComponent.razor
> +                                        var t = statusHistory.RequestStatusTime.Value.ToString(this.DateFormat);
var t doesn't seem to be used and could be removed.
```suggestion
```

2021-08-09 18:27 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/Entities/WorkloadRequestTableItem.cs
> +        public string RequestDateFormatted { get; set; }
Doesn't seem to be used and can be removed.
```suggestion
```

2021-08-09 18:27 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/MMEDetails.razor.cs
> +                Model.DateOfExpiry = CommonService.DateFormat(Model.ExpiryDate, "MMMM dd, yyyy");
I see this string repeated a lot, possibly add this to our constants class as a read-only parameter. "MMMM dd, yyyy"

2021-08-09 20:33 UTC, TC-Cory reviewed
Code looks good, Verifying front end

2021-08-10 13:55 UTC, TC-Cory reviewed
Front end looks good, code looks good as well

2021-08-10 13:55 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/Components/Tables/WorkloadRequest/WorkloadRequestTable.razor
> +                    @*<span>@GetLocalTime(WorkloadRequestTableItem.RequestDate).ToString("MMM d, yyyy - HH:mm", Culture)</span>*@
```suggestion
                  
```
we can remove commented code if not needed

2021-08-10 18:07 UTC, tc-chris commented on src/CSF.SRDashboard.Client/DTO/MpdisApplicantDto.cs
> +                return start.AddMilliseconds(this.DateOfBirth).ToLocalTime();
Why are we using local time and not UTC?

2021-08-10 18:07 UTC, tc-chris commented on src/CSF.SRDashboard.Client/Components/Seafarer/SeafarerProfileComponent.razor
> +                        <p>@CommonService.DateFormat(this.Applicant.ParsedDateOfBirth, "MMM dd, yyyy")</p>
Use Constants.MMM_DD_YYYY here

2021-08-10 18:23 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/DTO/MpdisApplicantDto.cs
> +                return start.AddMilliseconds(this.DateOfBirth).ToLocalTime();
Done!

2021-08-10 18:23 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/Seafarer/SeafarerProfileComponent.razor
> +                        <p>@CommonService.DateFormat(this.Applicant.ParsedDateOfBirth, "MMM dd, yyyy")</p>
Changed.

2021-08-10 18:35 UTC, tc-chris commented on src/CSF.SRDashboard.Client/Services/CommonService.cs
> +            var charsToRemove = new string[] { "." };
The period isn't in the UI so I remove it

2021-08-11 14:12 UTC, merged