Ab#108015 validation error warning
tc-ca/MSS-Seafarer-Certification pull request #195
Opened 2021-08-16 15:29 UTC by TC-Cory

2021-08-16 17:58 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/PageValidators/CssSetter.cs
> +    public class CssSetter : FieldCssClassProvider
SearchCssSetter seems to have the same is it possible to create one class for both?

2021-08-16 17:59 UTC, AlexandreSanscartier requested changes
Just one comment to consider before approving this.

2021-08-17 12:02 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/PageValidators/CssSetter.cs
> +    public class CssSetter : FieldCssClassProvider
it's been removed and merged into one

2021-08-17 14:01 UTC, tc-chris requested changes

2021-08-17 16:07 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/PageValidators/UploadDocumentAttachmentValidator.cs
> +            this.RuleFor(x => x.Language).NotEmpty().WithMessage("Please select a language");
Done, All validators have been localized

2021-08-17 16:07 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/PageValidators/RequestValidator.cs
> +            RuleFor(x => x.RequestType).NotEmpty().WithMessage("Please select a request type");
Done, All validators have been localized

2021-08-17 17:22 UTC, AlexandreSanscartier requested changes
Overall looks good, just a few name changes and one verification before closing this PR.

2021-08-17 17:22 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/DocumentInformation.razor
> +                        <InputMultipleSelect UseSelectedItemsAsSelectTitle="true" AdditionalCSS="@(this.FirstRender ? this.UploadedDocuments[i].IsValid ? "is-valid" : "is-invalid" : "")" Title="@Loca
There seem to be embedded inline booleans can we add a method for this so it's a bit less confusing at first glance?

2021-08-17 17:22 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/DocumentInformation.razor
> +                        @if (!this.UploadedDocuments[i].IsValid && this.FirstRender)
Perhaps create a method with an explicit name? For example, why does this need to be on the first render and also IsValid?

2021-08-17 17:22 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/DocumentInformation.razor.cs
> +                FirstRender = true;
I'm not sure I'd have to verify, but won't this always be true since we never explicitly set it to false?

2021-08-17 17:22 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/DocumentInformation.razor.cs
> +        private bool verifyDocumentTypes(UploadedDocument document) => document.DocumentTypeList.Where(i => i.Value).ToList().Any();
What exactly is this method doing? It seems to be just checking if the document has a documentType? If this is the case can we renamed it to something more explicit like HadDocumentTypes? Or DoesDocumentHaveDocumentTypes orr  something around those lines?

2021-08-17 17:22 UTC, AlexandreSanscartier commented on src/CSF.SRDashboard.Client/Components/DocumentInformation.razor.cs
> +        }
Here we seem to be setting the isValid flag only if the documentType is valid, so this method could be renamed to VerifyDocumentHasDocumentType or something like ValidateDocumentHasDocumentType or something around those lines.

2021-08-18 14:05 UTC, AlexandreSanscartier approved these changes

2021-08-18 17:49 UTC, merged