Ab#134701 global exceptions
tc-ca/MSS-Seafarer-Certification pull request #298
Opened 2021-12-13 20:28 UTC by TC-Cory

Hello everyone, this PR requires .net 6 and VS 2022 in order to test.

.net 6 SDK: https://dotnet.microsoft.com/en-us/download/dotnet/6.0
You can upgrade visual studio through the visual studio installer.

2021-12-14 20:43 UTC, tc-chris requested changes

2021-12-14 20:43 UTC, tc-chris commented on src/CSF.SRDashboard.Client/Components/UploadDocumentComponent.razor.cs
> +                throw new NullReferenceException(ErrorConstants.LoVError);
Doing the null check in the service method rather than here

2021-12-14 20:43 UTC, tc-chris commented on src/CSF.SRDashboard.Client/Pages/EditAttachment.razor.cs
> +                throw new NullReferenceException(ErrorConstants.ApplicantError);
Same thing here

2021-12-15 18:11 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/Components/UploadDocumentComponent.razor.cs
> +                throw new NullReferenceException(ErrorConstants.LoVError);
done

2021-12-15 18:11 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/Pages/EditAttachment.razor.cs
> +                throw new NullReferenceException(ErrorConstants.ApplicantError);
We need to verify within the component. If I throw the error within the service method, it will not display the page correctly

2021-12-15 19:32 UTC, TC-Cory commented on src/CSF.SRDashboard.Client/Pages/EditAttachment.razor.cs
> +                throw new NullReferenceException(ErrorConstants.ApplicantError);
Ok I've pushed a fix after some additional testing.

2021-12-15 20:10 UTC, tc-chris approved these changes

2021-12-15 20:15 UTC, merged