Feature/ab#44506 add file upload to mtoa
tc-ca/MSS-Seafarer-Certification pull request #89
Opened 2020-11-12 16:34 UTC by tropical-turtle

Added File upload service also wired up with virus scan work flow message.

2020-11-13 14:32 UTC, tc-chris requested changes

2020-11-13 14:32 UTC, tc-chris commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            int serviceRequestId = 13844; //13844 is for Dev. For Kanga use  15703
Maybe `int serviceRequestId = 13844;` can be a global or constant

2020-11-13 14:32 UTC, tc-chris commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +            int serviceRequestId = 13844; // this is used for Dev
Same thing here `int serviceRequestId = 13844;` should be public and not just a variable

2020-11-13 14:32 UTC, tc-chris commented on CDTS Blazor/Pages/UploadDocument.razor
> +                                @PageLocalizer["DocumentType"]: RecordHardcore
I thought you were gonna fix `@PageLocalizer["DocumentType"]: RecordHardcore` and remove the RecordHardcore text

2020-11-13 15:37 UTC, AlexandreSanscartier requested changes

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            int serviceRequestId = 13844; //13844 is for Dev. For Kanga use  15703
I added it in the appsettings.json in my code once it's pushed to dev we can integrate it.

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            Assert.True(isSuccess);
Remove: 
            bool isSuccess = false;
            if (attachment.Id > 0)
            {
                isSuccess = true;
            }
            else
            {
                isSuccess = false;
            }
            Assert.True(isSuccess);
Replace with:
Assert.True(attachment.Id > 0);

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            Assert.True(fileId > 0);
```suggestion
            Assert.True(attachment.Id > 0);
```

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +        public void MtoaFileServiceApiCleanDataTest()
Excerpt from the article.
>Naming your tests
>
> The name of your test should consist of three parts:
> 
> The name of the method being tested.
> The scenario under which it's being tested.
> The expected behavior when the scenario is invoked.

Refer to this document for a more detailed explanation: https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +        public void MtoaFileServiceMethodTest()
Excerpt from the article.
> Naming your tests
> 
> The name of your test should consist of three parts:
> 
> The name of the method being tested.
> The scenario under which it's being tested.
> The expected behavior when the scenario is invoked.
> 

Refer to this document for a more detailed explanation: https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +        public void MtoaFileServiceApiInfectedDataTest()
Excerpt from the article.

>Naming your tests
>
>The name of your test should consist of three parts:
>
>The name of the method being tested.
>The scenario under which it's being tested.
>The expected behavior when the scenario is invoked.

Refer to this document for a more detailed explanation: https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            #region Virus Test File
Would be more readable with a private method. something like createVirusFile() and we could move this block of code into that method.

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            int serviceRequestId = 13844; //13844 is a temporary service request id for Dev.
Seem to use the serviceRequest in every test method. Moving it to a private class variable would be prefereable.

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            Assert.True( isInfected );
```
            bool isInfected = false;
            if(uploadedFile.Id < 0)
            {
                isInfected = true;
            }
            else
            {
                isInfected = false;
            }


            Assert.True( isInfected );
```
And replace it with:
`Assert.True(uploadedFile.Id < 0);`

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDTS Blazor/Data/Services/MtoaEmailService.cs
> +        //private string base_uri_str = "https://wwwappstestext.tc.gc.ca/Saf-Sec-Sur/13/MTAPI-INT/"; // Kanga INT
Remove commented code.

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +        //private string base_uri_str = "https://wwwappstestext.tc.gc.ca/Saf-Sec-Sur/13/MTAPI-INT/api/v1/";
Remove commented code.

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +        // if there is a null value in the List<int>, it means that the corresponding file was not uploaded successfully. Like for a virus issue.
the int value type can not be null are we sure this is the behavior?

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +            if (fileAttachments.Count > 0)
Unnecessary the for loop will not run if the count is 0

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +            if (pageModel.UploadedFiles.Count > 0)
Unnecessary the for loop will not run if the count is 0

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +            int serviceRequestId = 13844; // this is used for Dev
Make this a class variable if used in more than one method.

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +        private List<FileAttachment> GetFileAttachmentsFromPageModelAsync(UploadDocumentPageModel pageModel, int serviceRequestId)
This should be renamed as it's not async and it's misleading.

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +                    ContentType = "testing",
should content type be testing?

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +                        ContentType = "testing",
Should contentType be testing?

2020-11-13 15:37 UTC, AlexandreSanscartier commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +        public async Task<FileAttachment> UploadFile(int serviceRequestId, FileAttachment fileAttachment)
We should probably create a PBI or issue to integrate the RestClient in the future.

2020-11-16 15:43 UTC, tropical-turtle commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            int serviceRequestId = 13844; //13844 is for Dev. For Kanga use  15703
In a perfect scenario, serviceRequestId  needs to be dynamically generated through another MTOA service call for each applicant. So it is why this was used as a variable. I believe this should not be stored as a constant since it is not a constant.
At some point when need to implement anther service call to MTOA to generate Service-Request-Id for each applicant related transactions.

2020-11-16 15:45 UTC, tropical-turtle commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +            int serviceRequestId = 13844; // this is used for Dev
In my oppenion as mentioned above, service request Id is not a public constant.

2020-11-16 15:51 UTC, AlexandreSanscartier commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            int serviceRequestId = 13844; //13844 is for Dev. For Kanga use  15703
Then we should build a service for this in order to get a ServiceRequestId and start using that service instead of the constants. #91 Issue created to keep track of this.

2020-11-16 15:56 UTC, tropical-turtle commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            int serviceRequestId = 13844; //13844 is for Dev. For Kanga use  15703
I raised this to @tc-tibo  in the past. He mentioned for MVP we could keep it simpler with a variable.

2020-11-16 15:57 UTC, tropical-turtle commented on CDTS Blazor/Pages/UploadDocument.razor
> +                                @PageLocalizer["DocumentType"]: RecordHardcore
Accepted changes from @tc-chris .

2020-11-16 16:15 UTC, tropical-turtle commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +        private List<FileAttachment> GetFileAttachmentsFromPageModelAsync(UploadDocumentPageModel pageModel, int serviceRequestId)
Good catch :) .  
It was Async at some point, when changed the method ,forgot to rename it.
Removed "Async" from method name.

2020-11-16 18:33 UTC, tropical-turtle commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +                        ContentType = "testing",
Added ContentType

2020-11-16 18:33 UTC, tropical-turtle commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +                    ContentType = "testing",
Added ContentType

2020-11-16 18:34 UTC, tropical-turtle commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +        public async Task<FileAttachment> UploadFile(int serviceRequestId, FileAttachment fileAttachment)
As per discussion. Kept it as is.

2020-11-16 18:41 UTC, tropical-turtle commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +        public void MtoaFileServiceApiCleanDataTest()
Change test method name.

2020-11-16 18:47 UTC, tropical-turtle commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +        public void MtoaFileServiceApiInfectedDataTest()
Test name changed

2020-11-16 18:49 UTC, tropical-turtle commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            Assert.True( isInfected );
Changed

2020-11-16 18:51 UTC, tropical-turtle commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +        //private string base_uri_str = "https://wwwappstestext.tc.gc.ca/Saf-Sec-Sur/13/MTAPI-INT/api/v1/";
Removed

2020-11-16 18:56 UTC, tropical-turtle commented on CDTS Blazor/Data/Services/MtoaEmailService.cs
> +        //private string base_uri_str = "https://wwwappstestext.tc.gc.ca/Saf-Sec-Sur/13/MTAPI-INT/"; // Kanga INT
Removed

2020-11-16 19:05 UTC, tropical-turtle commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +        // if there is a null value in the List<int>, it means that the corresponding file was not uploaded successfully. Like for a virus issue.
Corrected comment.
Good attention to details @AlexandreSanscartier

2020-11-16 19:11 UTC, tropical-turtle commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +            if (fileAttachments.Count > 0)
That method was written for a general purpose that there maybe multiple file selections through file browser dialog.
FileUploader seems to have restricted multiple file selection. and only one file was chosen on UploadDocument.razor.

Kept it as is for possible future use.

2020-11-16 19:12 UTC, tropical-turtle commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            int serviceRequestId = 13844; //13844 is a temporary service request id for Dev.
As per discussion. Kept it as is.

2020-11-16 19:15 UTC, tropical-turtle commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            #region Virus Test File
For not being dependent on another method while testing one. Kept it this way.

2020-11-16 19:18 UTC, AlexandreSanscartier commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            #region Virus Test File
I disagree this needs to be in a separate method. Prefer using private methods over regions. You can insert the private method right below the test method.

2020-11-16 19:22 UTC, AlexandreSanscartier commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +            if (fileAttachments.Count > 0)
Again you can remove the if statement as it's a useless check. The foreach does the same job that the if statement does. 

This:
```
    fileAttachmentIDs = new List<int>();
foreach (var file in fileAttachments)
{
      var storedFileAttachment = this.UploadFile(serviceRequestId, file); 
      fileAttachmentIDs.Add( storedFileAttachment.Id);
}
```
And This:
```
if (fileAttachments.Count > 0) {
    fileAttachmentIDs = new List<int>();
      foreach (var file in fileAttachments)
      {
          var storedFileAttachment = this.UploadFile(serviceRequestId, file); 
           fileAttachmentIDs.Add( storedFileAttachment.Id);
       }
}
```
Are functionally the same thing, but one of them is more lines of code.

2020-11-16 22:16 UTC, tropical-turtle commented on CDNApplication.Tests.Integration/MtoaFileServiceTest.cs
> +            #region Virus Test File
That test was created based on the test that MTOA developers provided.

2020-11-16 22:18 UTC, tropical-turtle commented on CDTS Blazor/Data/Services/MtoaFileService.cs
> +            if (fileAttachments.Count > 0)
Changed

2020-11-16 23:17 UTC, AlexandreSanscartier approved these changes

2020-11-16 23:24 UTC, AlexandreSanscartier approved these changes

2020-11-16 23:27 UTC, merged